### ISSUE TITLE
The code part is not exist

### ISSUE THREAD

**Issue by slona-song** [Jiaxin-Ye/TIM-Net_SER#1]
hi, thanks for your sharing. and you really do a exellent job.
but there is no code file in this repository, when will the code be updated?

Thanks again!

**Comment by Jiaxin-Ye** [comment]
Thanks for your attention! We are willing to open-source our code in the next month for your better experience. We apologize for any inconvenience caused to you. Please look forward to it shortly.

Thanks again!

**Comment by nikich340** [comment]
> Thanks for your attention! We are willing to open-source our code in the next month for your better experience. We apologize for any inconvenience caused to you. Please look forward to it shortly.
> 
> Thanks again!

Hello, any updates! Also, is it possible to publish your pretrained model for testing? Thanks in advance.

**Comment by SanjayDevTech** [comment]
Hi Any updates @Jiaxin-Ye Thanks in advance. :)

**Comment by OswaldoBornemann** [comment]
Hi Any updates ?

**Comment by Jiaxin-Ye** [comment]
Hi, sorry to keep you waiting, the datasets, source code, and pre-trained models are available at https://github.com/Jiaxin-Ye/TIM-Net_SER, thanks for your attention to our work!

Best wishes,
Jiaxin Ye

**Comment by Jiaxin-Ye** [comment]
Hi, sorry to keep you waiting, the datasets, source code, and pre-trained models are available at https://github.com/Jiaxin-Ye/TIM-Net_SER, thanks for your attention to our work!

Best wishes,
Jiaxin Ye
