### ISSUE TITLE
Is the feature of iemocap about dialogue or sentence？

### ISSUE THREAD

**Issue by huhnwe** [Jiaxin-Ye/TIM-Net_SER#10]
Is the feature of iemocap about dialogue or sentences, and also the source code of extracting the mfcc feature of iemocap can be read?

**Comment by Jiaxin-Ye** [comment]
Thanks for your attention.
1. the features of IEMOCAP are about sentences (i.e., 5531 features correspond to 5531 speech signals)
2. you can refer it in README.

**Comment by huhnwe** [comment]
> Thanks for your attention.
> 
> 1. the features of IEMOCAP are about sentences (i.e., 5531 features correspond to 5531 speech signals)
> 2. you can refer it in README.

Thank you for your reply！You do a excellent work.
