### ISSUE TITLE
About the visualize of results and Figure 

### ISSUE THREAD

**Issue by yihaoyao402** [Jiaxin-Ye/TIM-Net_SER#17]
Thank you for your outstanding work on speech emotion recognition! I still have a small problem with the code, after I train the model and successfully test it with 10 folds, I don't know how to visualize the training process and save the results, just like the picture in your Fig. I don't seem to find the part of the code where the results are plotted, so I'd like to ask you how to plot the Fig. Thank you very much!

**Comment by Jiaxin-Ye** [comment]
I appreciate your interest in our work! If you want to visualize the training process, you can save the log first, and then use the following regular expressions to match specific patterns; or use packages such as Wandb to record and output.

```python
val_loss_pattern = re.compile(r'val_loss: ([0-9.]+)')
val_accuracy_pattern = re.compile(r'val_accuracy: ([0-9.]+)')
train_loss_pattern = re.compile(r'loss: ([0-9.]+)')
train_accuracy_pattern = re.compile(r'accuracy: ([0-9.]+)')
```
