### ISSUE TITLE
pre-trained models

### ISSUE THREAD

**Issue by hsnr-nana** [Jiaxin-Ye/TIM-Net_SER#2]
Dear authors! Thanks for your great work! Could you kindly upload your pre-trained models outside of baidu, e.g., on Google Drive as i am facing difficulty for downloading it?

**Comment by Jiaxin-Ye** [comment]
https://drive.google.com/drive/folders/1ZjgcT6R0A0C2twXatgpimFh1a3IL81pw?usp=share_link

**Comment by Jiaxin-Ye** [comment]
Of course! This is the  [Google Drive](https://drive.google.com/drive/folders/1ZjgcT6R0A0C2twXatgpimFh1a3IL81pw?usp=share_link) link that contains pre-trained models. If you have any questions, please feel free to contact me, and I will be honored to answer your questions.
