### ISSUE TITLE
Equation (3) of paper is inconsistent with Code

### ISSUE THREAD

**Issue by vtsouval** [Jiaxin-Ye/TIM-Net_SER#3]
Hello and thank you for open sourcing your code. I have noticed an inconsistency between Fig.1 and Equation 3 of your paper. Specifically, the outputs of the two TAB blocks are [added](https://github.com/Jiaxin-Ye/TIM-Net_SER/blob/main/Code/TIMNET.py#L90) and then passed though the [GlobalAveragePooling1D layer](https://github.com/Jiaxin-Ye/TIM-Net_SER/blob/main/Code/TIMNET.py#L91) in your code (and Figure), while in Equation 3 you describe them in the reverse order. Can you clarify this for me?
Thank you again for your vital contribution to the research community.

**Comment by Jiaxin-Ye** [comment]
Hi! Thank you for indicating the issue. Although the output obtained from both calculations is consistent, the formulation of the paper is not well presented. We have fixed this issue in our latest version (camera-ready version). I think that answers your question. 

Thanks again.
