### ISSUE TITLE
MFCC features files

### ISSUE THREAD

**Issue by jissss333** [Jiaxin-Ye/TIM-Net_SER#4]
Hello, thank you for your great work and sharing!

However, I'm facing difficulty to download MFCC features files from Baidu. (It is not easy to make Baidu account 😂)
Could you upload MFCC features files with Google Drive?

Thank you!

**Comment by cate865** [comment]
Facing a similar issue. A Google Drive link for this would be very helpful. Thanks!

**Comment by Jiaxin-Ye** [comment]
Sorry to keep you waiting! This is the [Google Drive](https://drive.google.com/drive/folders/1nl7hej--Nds2m3MrMDHT63fNL-yRRe3d) link that contains our MFCC features.

Best regards.
