### ISSUE TITLE
Questions about the format of the dataset

### ISSUE THREAD

**Issue by wangjialin97** [Jiaxin-Ye/TIM-Net_SER#6]
Thanks for your excellent job, I'm very appreciative of it. But there is a question about the format of the dataset. Is your dataset split by labels or by train/validation? Thanks a lot.

**Comment by Jiaxin-Ye** [comment]
Thanks for your attention! The dataset are splited by 10-fold cross validation (train/validation). Specifically, you can see the source code as follows:
https://github.com/Jiaxin-Ye/TIM-Net_SER/blob/73488c8db586e749c46a63678e858b05d6d2f1a1/Code/Model.py#L99
https://github.com/Jiaxin-Ye/TIM-Net_SER/blob/73488c8db586e749c46a63678e858b05d6d2f1a1/Code/Model.py#L102
